services:

  maria:
    # JDBC_URL: 'jdbc:mariadb://localhost:3306'
    # USERNAME: 'root'
    # PASSWORD: 'root'
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  postgresql:
    # JDBC_URL: 'jdbc:postgresql://localhost:5432/public'
    # USERNAME: 'root'
    # PASSWORD: 'root'
    image: postgres
    environment:
      POSTGRES_DB: public
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    command: postgres -c 'max_connections=1000'
    ports:
      - 5432:5432

  mysql:
    # JDBC_URL: 'jdbc:mysql://localhost:3307'
    # USERNAME: 'root'
    # PASSWORD: 'root'
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307

  mssql:
    # JDBC_URL: 'jdbc:sqlserver://localhost:1433;encrypt=false;'
    # USERNAME: 'sa'
    # PASSWORD: 'Root_root1'
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Root_root1
    ports:
      - 1433:1433

  db2:
    # JDBC_URL: 'jdbc:db2://localhost:50000/main'
    # USERNAME: 'db2inst1'
    # PASSWORD: 'root'
    container_name: db2
    image: icr.io/db2_community/db2
    privileged: true
    environment:
      - LICENSE=accept
      - DB2INSTANCE=db2inst1
      - DB2INST1_PASSWORD=root
      - DBNAME=main
      - BLU=false
      - ENABLE_ORACLE_COMPATIBILITY=false
      - UPDATEAVAIL=NO
      - TO_CREATE_SAMPLEDB=true
      - REPODB=false
      - IS_OSXFS=false
      - PERSISTENT_HOME=false
      - HADR_ENABLED=false
    ports:
      - 50000:50000

  oracle:
    # JDBC_URL: 'jdbc:oracle:thin:@localhost:1521:XE'
    # USERNAME: 'system'
    # PASSWORD: 'root'
    container_name: oracle
    ports:
      - 1521:1521
    image: gvenzl/oracle-xe:18-slim
    environment:
      - ORACLE_PASSWORD=root
